name: Main Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
        
    - name: Checkout Juego
      uses: actions/checkout@v3
      with:
        path: Juego
        
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:
          7.0.x
    
    - name: Build Juego
      run: dotnet build -c Release Juego/Source/Juego.sln
